### ISSUE TITLE
Payment Checkout problem

### ISSUE THREAD

**Issue by DMJain** [cashfree/cashfree-sdk-nodejs#48]
Having issues with payment checkouts in my project
I also tried from https://www.cashfree.com/devstudio/preview/pg/web/popupCheckout but got the same error

![image](https://github.com/user-attachments/assets/e4070831-3465-4fd5-9649-8818051d7fe9)

It seems like a server issue
![image](https://github.com/user-attachments/assets/b944ad72-32ed-46c9-841d-912d40e2c305)
but it also says PaymentJSInterface is undefined.

Would someone be able to help me with this? is cashfree down or is it an actual problem? A few hrs ago it was working fine.

**Comment by Harshith-CF** [comment]
this is an intermittent issue at our end, it is resolved now

**Comment by DMJain** [comment]
I tried again, cleared the cache, hard reloaded, and tried another browser, but the issue persisted. I will try again tomorrow.

**Comment by Harshith-CF** [comment]
Did you checked it now?

**Comment by DMJain** [comment]
yes. i tried in my project and cashfree devStudio.

![image](https://github.com/user-attachments/assets/65b4906d-8b98-4777-a8d2-53bcbc9cd28e)

**Comment by Harshith-CF** [comment]
Can you recheck now

**Comment by DMJain** [comment]
Working perfectly
